### ISSUE TITLE
reaction prediction example

### ISSUE THREAD

**Issue by drc007** [rxn4chemistry/rxn4chemistry#1]
I found print results should be

print(results['response']['payload']['attempts'][0]['smiles'])

**Comment by drugilsberg** [comment]
Thanks for reporting this @drc007. Will update immediately.

**Comment by drugilsberg** [comment]
Thanks again updated :).

**Comment by drc007** [comment]
Great, just FYI

https://twitter.com/macinchem/status/1247978658398195712 <https://twitter.com/macinchem/status/1247978658398195712>

Chris
