### ISSUE TITLE
availability / pricing threshold units

### ISSUE THREAD

**Issue by ltalirz** [rxn4chemistry/rxn4chemistry#15]
I have two questions concerning the availability pricing threshold for retrosynthesis:

 1. I notice in the GUI that the units are USD per "mg/mL".
![image](https://user-images.githubusercontent.com/1053245/101383919-1017cd80-38ba-11eb-8915-7603f0afc329.png)

    Is this really the case or is it "g/mL"? 
    At least if one assumes the density of water, then 1mL = 1000 mg

 2. I notice that the type of the parameter is "int"
https://github.com/rxn4chemistry/rxn4chemistry/blob/b8601cecdfdeeb45cefacca9bf8945e478d290fa/rxn4chemistry/core.py#L316
    Is there a particular reason for going with int over float here?
    It is true that emolecules quotes their prices in full dollars, but it's often for larger batches than 1mg.
    $1/mg is already $1 million per kg (even $1/g is still $1000/kg), and I would guess the main use of the price threshold in the API would be to filter out "expensive ingredients", i.e. being able to specify the lower price range matters

**Comment by drugilsberg** [comment]
HI @ltalirz, very good question. The main reason resides in the fact that the API we expose performs a validation for integer values (https://rxn.res.ibm.com/rxn/api/v2/api-docs, see `RetrosynthesisRequestParameters`).
Very good point for the price listings from eMolecules. I'm involving here @pschwllr that might have a better intuition behind this design option.
BTW, thanks a lot for the interest in our work.

**Comment by drugilsberg** [comment]
Hey @ltalirz, thanks a lot for raising this point, it's indeed a case of a problematic interface to apply a meaningful filter on commercial precursors. After some internal discussions with @pschwllr and other team mebers, we will adapt the slider and the API to handle floating point values expressed as USD over g or mL. As soon as the modification is rolled out we will open a PR here to address the issue in the repo.

**Comment by ltalirz** [comment]
Thanks for the prompt reply, looking forward to it!

**Comment by drugilsberg** [comment]
Dear @ltalirz thanks a lot again for reporting this and sorry for the long silence. After some internal discussion we decided to adapt all units to g/mL (still leaving the type to integer, since we did not feel that going below dollars would be useful). The web service already reflects this, the python package has a PR that simply updates the relative documentation: https://github.com/rxn4chemistry/rxn4chemistry/pull/21.
Closing, feel free to reopen.
