### ISSUE TITLE
Issues with Processing Molecules for Retrosynthesis

### ISSUE THREAD

**Issue by eereenah-fast** [rxn4chemistry/rxn4chemistry#24]
Hello, thanks a lot for sharing your project! It has really been of great help!

I am not sure whether this is the right place to ask this question but I am having issues with processing molecules for retrosynthesis. Once I submit a new molecule, its status is stuck on `NEW`. 

This is what I see on the website (this message has been the same for two days):
![screenshot](https://user-images.githubusercontent.com/65531744/112428145-260baa00-8d54-11eb-9a6b-61ab560cb68c.png)

Do you know any workarounds or what exactly may be causing this issue? 
Thanks a lot in advance!

**Comment by drugilsberg** [comment]
Hi @eereenah-fast, totally fine to ask the question here. Thanks for reaching out.
I see two potential causes:

1. the jobs got queued and never picked up by the workers running the retrosynthesis (unlikely)
2. the jobs failed with an unexpected error without acknowleding the web GUI (rare, but more likely)

Unfortunately, we don't have access to the user's job submission so this makes debugging a little bit more complicated.

To better help you and understand the issue you are encountering it would be great if you can share with us some details to reproduce the behaviour:

- input molecule for retrosynthesis
- parameters used for the retrosynthesis (even the Speed/Quality Tuning slider would be enough, see image below)
![image](https://user-images.githubusercontent.com/5406908/112430416-695b1e00-8d3e-11eb-824b-771308af1778.png)

**Comment by eereenah-fast** [comment]
These are example molecules that are stuck in the queue at the moment:

- Cc1cc(C(C=O)=CCO)cc(-c2cc(C)cnn2)c1
- Cc1cnnc(-c2cc3c(C)c(CN)oc3c(C(C)O)c2O)c1C

The parameters are:

- **MSSR**: 3
- **MRP**: 50
- **FAP**: 0.65
- **SbP**: 3
- **USD**: 0

For the first molecule, this dialog window is currently displayed:
![image](https://user-images.githubusercontent.com/65531744/112438576-805f3780-8d61-11eb-8d96-1392fca45e21.png)

**Comment by drugilsberg** [comment]
Thanks a lot we will investigate and let you know

**Comment by drugilsberg** [comment]
With the first molecule I wasn't able to reproduce the behavior.

The retrosynthesis fail with the given parameters but the job is not getting stuck.
![image](https://user-images.githubusercontent.com/5406908/112449373-9b2aaf80-8d53-11eb-87ba-1ab25e065021.png)

I tried with the interactive mode (no FAP basically) and you can find a super low confidence route (keep in mind that the low confidence usually means chemical unfeasibility)
![image](https://user-images.githubusercontent.com/5406908/112449506-be555f00-8d53-11eb-8f4f-68b2ce5d5e76.png)

Taking a look now at the second.

**Comment by drugilsberg** [comment]
Even for the second molecule I'm unable to reproduce the bug.

See here the result with the parameters you shared.
![image](https://user-images.githubusercontent.com/5406908/112450668-e85b5100-8d54-11eb-9b2e-e8b4585ffcb8.png)

The retrosynthesis runs through and stops at the maximum MSSR set (3).

**Comment by drugilsberg** [comment]
The issue seems to be not reproducible, I'm leaning towards thinking that the jobs got lost due to a high system load.
@eereenah-fast Could you please try to rerun them? Just want to make sure it's not something related to your specific user account.

**Comment by eereenah-fast** [comment]
Thank you for the reply and apologies for responding so late. I tried rerunning the molecules again on Friday and the job got stuck in queue but I tried submitting them once again and the job did finish successfully, so I guess it really had something to do with the high system load. Thanks a lot for your assistance!

**Comment by drugilsberg** [comment]
Hi @eereenah-fast, no worries at all and thanks a lot for your interest and for using the platform 🙏
