### ISSUE TITLE
[Errno 11001] getaddrinfo failed error

### ISSUE THREAD

**Issue by thatkidsampson** [rxn4chemistry/rxn4chemistry#3]
Hello!

I'm running rxn4chemistry in Jupyter lab and I'm getting a connection error which doesn't happen  when I run make the same request using request.get.

If I try to list all projects, with rxn4chemistry for example:

`rxn4chemistry_wrapper = RXN4ChemistryWrapper(api_key=api_key) 
 rxn4chemistry_wrapper.list_all_projects()`

I get a long error message that ends with:

`ConnectionError: HTTPSConnectionPool(host='rxn.res.ibm.com%5crxn', port=443): Max retries exceeded with url: /api/api/v1%5Cprojects (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00007FF45ADE8848>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))`

However, if I run:

`headers = {"Authorization":api_key, "Content-Type": "application/json"}
                         
url = "https://rxn.res.ibm.com/rxn/api/api/v1/projects?page=0&size=30"   
        
response = requests.request("GET", url, headers=headers)         

print(response)`

Then I get a good response code: `<Response [200]>` and `print(response.json())` returns:

`{'payload': {'content': [], 'totalPages': 0, 'last': True, 'totalElements': 0, 'sort': None, 'numberOfElements': 0, 'first': True, 'size': 30, 'number': 0}, 'metadata': {'uiMessages': {'errors': [], 'infos': [], 'warnings': []}, 'extendedPagination': {}}}`

I'm working in JupyterLab v1.2.6 on Windows 10 in Chrome. 
Python version 3.7.7, RXN4chemistry v  0.1.4.

**Comment by drugilsberg** [comment]
@thatkidsampson I think it's an issue related to windows, let me look into it.  I will open a PR soon. Keeping you posted.

**Comment by drugilsberg** [comment]
@thatkidsampson the issue with URLs handling in windows should be solved in the latest package version.
Please let me know if the problem is solved and if we can close the issue.
To verify install:
```python
pip install rxn4chemistry==0.1.5
```
Or upgrade the package:
```python
pip install -U rxn4chemistry
```

**Comment by thatkidsampson** [comment]
That has fixed it, it's working great now, thank you!
