### ISSUE TITLE
list_all_retro_attempts_in_project() method of RXN4ChemistryWrapper returns error from server

### ISSUE THREAD

**Issue by adhardy** [rxn4chemistry/rxn4chemistry#35]
Minimal example:

```
import logging
import sys
logging.basicConfig(level=logging.INFO, format='%(name)s - %(levelname)s - %(message)s', stream=sys.stderr)

import rxn4chemistry as rxn

api_key = ******
project_id = ******

wrapper = rxn.RXN4ChemistryWrapper(api_key=api_key, project_id=project_id)

wrapper.list_all_retro_attempts_in_project()
```
Returns:
```
python-2022.0.1786462952/pythonFiles/lib/python/debugpy/launcher 42107 -- /home/adam/projects/retrosynthesis/thieme/IBM_Thieme/rxn4chem.py 
rxn4chemistry.decorators - ERROR - Unexpected error.
NoneType: None
rxn4chemistry.decorators - ERROR - {"payload":null,"metadata":{"uiMessages":{"errors":[{"code":"GENERIC","message":"Generic error","type":"ERROR","fieldId":null,"target":"TOAST"}],"infos":[],"warnings":[]},"extendedPagination":{}}}
```

I am able to get this to work, but possibly not in the desired way, by changing:

```
self.retro_attempts_url = "{}/{}/{}".format(
    self.project_url, "{project_id}", "retrosynthesis-attempt"
)
```

in urls.py to 

```
self.retro_attempts_url = "{}/{}/{}".format(
    self.project_url, "{project_id}", "retrosynthesis"
)
```

and removing the "sort" entry in the payload dictionary in the list_all_retro_attempts_in_project() method of the wrapper.

I get a similar error using list_all_attempts_in_project() but that might just be because I don't have any forward predicition results on my account.

**Comment by drugilsberg** [comment]
hey @adhardy thanks a lot for reporting this, we will get back to you as soon as possible :)

**Comment by drugilsberg** [comment]
We recently had a REST API specs update that broke compatibility with the python client for attempt listing.
Thanks for catching this behaviour.
As soon as this PR passes the required checks, we will release a new version of the package that solves the issue: https://github.com/rxn4chemistry/rxn4chemistry/pull/36
