### ISSUE TITLE
The concept of precursor in rxn

### ISSUE THREAD

**Issue by Eason51** [rxn4chemistry/rxn4chemistry#43]
I have noticed the word "precursor " has occured in the parameter explanation of the retrosynthesis function. e.g. pricing: pricing of the precursors, exclude smiles: smiles of precursor to be excluded. I am not familiar with the chemistry aspect, so I wonder does the word "precursor" only refers to the leaf molecules of a retrosynthesis pathway? Or it refers to any molecule that appeared in the retrosynthesis tree. For example, if I have a two-step retrosynthesis pathway to synthesise compound A: 
First step: A -> B, C, D
Second step: B -> E, F
The leaf molecules are C, D, E, F, while B is not, so I wonder if the constraints set on precursors will be applied to compound B? For example, if I limit the price to be no larger than 100, then if B has a price greater than 100, will it be accepted, given that B will not appear in the leaf?

In addition, I wonder if the API is capable of performing interactive retrosynthesis planning? Or is automatic retrosynthesis planning using the API, setting the max_step parameter to 1, generates exactly the same result as when I perform interactive retrosynthesis using the rxn website?

Thank you very much!

**Comment by drugilsberg** [comment]
Hi @Eason51, that parameter only refers to leaf nodes. In your example B is an intermediate that is not available in the pricing database we use.

As of now the interactive retro is not available via the python client. In general you can obtain the same results (make sure you use the same ai model), but you have to lower the FAP parameter to avoid pruning reactions below the confidence threshold.

Feel free to reopen in case you have further questions.
