### ISSUE TITLE
Molecule Metadata meaning

### ISSUE THREAD

**Issue by Eason51** [rxn4chemistry/rxn4chemistry#44]
I wonder what some of the fields mean in the returned dictionary of a molecule.

Specifically, what is the meaning of the field, "isTouched".

In addition, what are the differences between the fields "isExpandable", "isCommercial", and "molecule2commercial" and "molecule2expandable" in the "metaData" field.

Thank you very much!

**Comment by drugilsberg** [comment]
Hi @Eason51, thanks for using RXN :).

Good question, the metaData carried Info on the molecule in the context of the retrosynthetic tree that are mostly used in the UI.

Here a brief description of the fields:
- isTouched: indicates whether a molecule has been selected/clicked by the user.
- isExpandable: is a boolean that indicates whether the molecule can be further disconnected. Usually we prevent disconnections of simple or readily available molecules.
- isCommercial: is a boolean indicating whether the molecule is commercially available in eMolecules.
- molecule2commercial and molecule2expandable: dictionaries mapping SMILES to boolean carrying the info in the two previous points.

When using the API or the python client, I would say that the most important fields are isExpandable and isCommercial, as they can be used to inspect whether the precursors are indeed available.
