### ISSUE TITLE
Batch submit from example code no longer works

### ISSUE THREAD

**Issue by grd36** [rxn4chemistry/rxn4chemistry#46]
response = rxn4chemistry_wrapper.predict_reaction_batch(precursors_list=['BrBr.c1ccc2cc3ccccc3cc2c1', 'Cl.c1ccc2cc3ccccc3cc2c1']*5)
comment/wait for the predictions to complete
time.sleep(2)
print(rxn4chemistry_wrapper.get_predict_reaction_batch_results(response["task_id"]))

=> leads to a  KeyError: task

predict_rection_batch_response = rxn4chemistry_wrapper.predict_reaction_batch(
    precursors_list=['BrBr.c1ccc2cc3ccccc3cc2c1', 'Cl.c1ccc2cc3ccccc3cc2c1']
)
for reaction_prediction in rxn4chemistry_wrapper.get_predict_reaction_batch_results(
    predict_rection_batch_response['task_id']
)['predictions']:
    print(f'Confidence: {reaction_prediction["confidence"]}')
    display(get_reaction_from_smiles(reaction_prediction['smiles']))

=> leads to a KeyError: predictions

These were working about 1-2 months ago.

**Comment by drugilsberg** [comment]
Thanks @drugilsberg we are actively working on a fix.

**Comment by drugilsberg** [comment]
As per the email conversation here an example on how running a large number of reactions (I added some logic to follow the task using `polling2` and `loguru` for the logging, you can pip install those easily):

```python
import polling2
import time
from loguru import logger
# NOTE: define api_key, rxn_url, model_version and precursors_list
rxn4chemistry_wrapper = RXN4ChemistryWrapper(api_key=api_key, base_url=rxn_url)
submission_response = rxn4chemistry_wrapper.predict_reaction_batch(
    precursors_list=precurors_list,  # NOTE: this list can contain up to 256 precursors sets (depending on the system load the number might be too high, so you can start with 64)
    ai_model=model_version
)
time.sleep(1)
try:
    check_response = polling2.poll(
        lambda: rxn4chemistry_wrapper.get_predict_reaction_batch_results(submission_response["task_id"]),
        step=polling_time,
        check_success=lambda response: "predictions" in response,  # NOTE: here you can put the logic you prefer
        timeout=60
    )
except polling2.TimeoutException:
    logger.exception(f"timeout error for task: {submission_response['task_id']}!")
    time.sleep(polling_time)
# check_response here contains the latest call before the termination condition set in check_success
```
Basically this submit a batch and checks every minute for the completion

**Comment by drugilsberg** [comment]
@grd36 the issue has been resolved, the server response changed erroneously but now it has been reverted.
The code posted above and your code using rxn4chemistry==1.6.0 should work completely fine.
