### ISSUE TITLE
Batch submit question

### ISSUE THREAD

**Issue by grd36** [rxn4chemistry/rxn4chemistry#48]
I wanted to ask if there are optimal polling or time.sleep times when doing batch submits. If I submit more than 10-20 rxns in a precursor list, I'm getting no response for about 75 seconds of wait time. 

Also, if one of the rxn's returns an exception error (such as ExceptionError, would this be added into the try and except logic?

Sorry about the questions, having a lot of trouble with wait times and formatting for precursors lists to read in a large amount of rxns.

**Comment by avaucher** [comment]
Hi @grd36,
Thanks for the question, and sorry already that my answer will not be of much help ;) 

It is hard to predict how long a prediction is going to take, as it depends on the current load of the server. It is indeed possible that it takes over one minute, depending on the size of the batch. The best thing to do is to poll every now and then (as you are probably already doing).

At the moment, I think that the call will return an error if any of the inputs is invalid (or rather: non-canonical). This is something I will look into, but it may take some time to improve.

**Comment by grd36** [comment]
Sorry thought I responded, thanks for the reply!
