### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hongxianglics** [rxn4chemistry/rxn4chemistry#58]
Hi,

I am using the tool with the code below
<img width="516" alt="IBM not working" src="https://user-images.githubusercontent.com/104338096/221075407-4d840ad8-6a24-4a05-86fd-b61b3684fb5f.PNG">
however I got the error. I tried to create a new project with the code`rxn4chemistry_wrapper.create_project('validation2')` but it tells me I shoud set the project(see fighre below)
<img width="719" alt="ibm not working 2" src="https://user-images.githubusercontent.com/104338096/221075652-cc4954dd-c34c-4947-8041-c3cdc66a08e3.PNG">
so I tried to set a project with the code `rxn4chemistry_wrapper.set_project('validate')`, then it comes another problem said the key called`'prediction_id'` not exist(see figure below)
<img width="590" alt="ibm not working3" src="https://user-images.githubusercontent.com/104338096/221075942-72ed734e-7f6f-49e8-af96-b76b281bb700.PNG">
and when go to the rxn4chemistry web server, I found the project was not created at all. I am confused and hope you can help me solve this problem. 
I am also confused because I tried the exactly same code several days ago and it worked well, but it failed today. I wonder is there some chenges in the server that I need to change the code?

Thanks in advance!

Hongxiang

**Comment by drugilsberg** [comment]
Hi @hongxianglics, thanks for reporting this and using our library.

Recently there was a change of url for the service and older versions of the package still points to the previous one.
I recommend to simply update the package to the  latest version using: `pip install --upgrade rxn4chemistry`.

Give it a try and feel free to reopen the issue in case you still have problems.
