### ISSUE TITLE
add flag for commercial availability

### ISSUE THREAD

**Issue by drugilsberg** [rxn4chemistry/rxn4chemistry#6]
Implement a processing of the retro response to avoid to use the border color as a proxy for commercial availability

**Comment by ltalirz** [comment]
Would you like to to parse the colors into the `isCommercial` field?
If that's the plan, I'm happy to add it.

**Comment by drugilsberg** [comment]
Hi @ltalirz if you want to go on and implement it feel free to open a PR, this is a very good first issue :)

**Comment by drugilsberg** [comment]
Great job @ltalirz, merged and bumped new version. As soon as the CI passes this should be available in the version 0.3.2 available from PyPI.
