### ISSUE TITLE
Request for guidance on integrating IBM RXN services using the Python wrapper

### ISSUE THREAD

**Issue by AlmaEvans2910** [rxn4chemistry/rxn4chemistry#60]
I am a beginner developer who is currently exploring the use of the IBM RXN services. I came across your Python wrapper on GitHub and I am interested in using it to integrate the IBM RXN services into my flutter application, but I am not sure how to proceed.

As a beginner, I was wondering if you could provide some guidance on how to use the wrapper to integrate the IBM RXN services, or if there are any examples or tutorials available that I could refer to. I would appreciate any help or advice that you could provide.

**Comment by drugilsberg** [comment]
@AlmaEvans2910 thanks for the interest in our work there a couple of resources you can use.

A good entry point is the [README.md](https://github.com/rxn4chemistry/rxn4chemistry/blob/main/README.md) of the repo.

In the folder called [examples](https://github.com/rxn4chemistry/rxn4chemistry/tree/main/examples) you will find some more extended tutorials you can follow (I would start from the [rxn4chemistry_tour.ipynb](https://github.com/rxn4chemistry/rxn4chemistry/blob/main/examples/rxn4chemistry_tour.ipynb)).

**Comment by AlmaEvans2910** [comment]
Thank you for getting back to me regarding my issue on the GitHub repository. I appreciate your suggestions on using the resources available in the README.md and the examples folder.

However, as a beginner, I am still struggling with how to use the Python wrapper in my Flutter project. I would greatly appreciate it if you could provide some guidance on how to integrate the Python wrapper with my Flutter application.

If there are any specific tutorials or examples available that demonstrate how to use the Python wrapper with Flutter, that would be extremely helpful.

Thank you again for your time and consideration. I look forward to hearing from you.

**Comment by drugilsberg** [comment]
I appreciate your interest in our work. Integrating a Python library into a Flutter application can be challenging, and unfortunately, I am not able to provide guidance on how to do so. However, Flutter has excellent documentation and tutorials that can help you integrate Python into your project. I recommend exploring those resources or seeking guidance from the Flutter community. Best of luck with your project.

This seems a relevant project: https://flet.dev
