### ISSUE TITLE
Too Many Requests Error for Automatic Retrosynthetic Prediction despite Staying within Rate Limit

### ISSUE THREAD

**Issue by LeenFahoum** [rxn4chemistry/rxn4chemistry#72]
I am encountering an issue with the Automatic Retrosynthetic Prediction feature on the platform. Despite adhering to the specified rate limit of five requests per minute, I consistently receive a "Too Many Requests" error message.
![image](https://github.com/rxn4chemistry/rxn4chemistry/assets/140955217/1a3912e3-54df-4411-aa05-e5d06ec9e0f6)

Could the team kindly  provide assistance in resolving this issue? Your help in resolving this issue is highly appreciated. Thank you!

**Comment by drugilsberg** [comment]
Thanks for opening an issue, please insert a `time.sleep(1)` after the `create_project` call as we have also rate limits that are imposing a maximum of two calls per second. This should address the problem you observe.
If this solves the problem, please close the issue.
