### ISSUE TITLE
cannot get "node_resp"

### ISSUE THREAD

**Issue by summmerF** [rxn4chemistry/rxn4chemistry#74]
Hi, 
When I use RXN4ChemistryWrapper, I can get "response" and  "results" correctly, and "create_synthesis_from_sequence" is also correct. But then when I use "get_node_ids" and "get_reaction_settings" functions, it's always like that
![image](https://github.com/rxn4chemistry/rxn4chemistry/assets/94446867/2d083179-c5e9-4f29-ac0c-bee9c68986b4)
I've tried many times, and it's the same results. 
Why is that and how to solve it? Thanks!

**Comment by drugilsberg** [comment]
Hi @summmerF thanks for using RXN.

From your screenshot it’s difficult to see which error you are exactly getting.

Can you paste here the full response?

**Comment by summmerF** [comment]
Yes, the full response:
`{"prediction_id": "65f5933a9d16ec001fea41a2", "response": {"payload": {"id": "65f5933a9d16ec001fea41a2", "metadata": {}, "embed": {}, "computedFields": {}, "createdOn": 1710592826467, "createdBy": "f4448e77-fcf6-4f49-b3b4-4fa250772dd4", "modifiedOn": 1710592826572, "modifiedBy": "f4448e77-fcf6-4f49-b3b4-4fa250772dd4", "projectId": "6597fcf90fb57c001f9699bb", "project": {"createdOn": 1704459513073, "createdBy": "f4448e77-fcf6-4f49-b3b4-4fa250772dd4", "modifiedOn": 1704459513073, "modifiedBy": "f4448e77-fcf6-4f49-b3b4-4fa250772dd4", "name": "test_0", "description": null, "visibility": null, "collectionDB": "", "id": "6597fcf90fb57c001f9699bb"}, "status": "NEW", "errorMessage": null, "task": {"finished_time": 0.0, "metaData": {}, "queued_time": null, "started_time": 0.0, "status": "WAITING", "expected_start": 0.0, "queue_position": 0, "task_id": "9345564a-fb4c-4421-95f1-454a84649310", "retrieval_time": 0.0, "retry": 0, "counters": {"backward_prediction": 0, "forward_prediction": 0}}, "molecules": [], "sequences": [], "sequencesIds": null, "legend": [{"color": "#002d9c", "label": "Common molecule available by default"}, {"color": "#0f62fe", "label": "Molecule available using a model-specific database"}, {"color": "#28a30d", "label": "Molecule commercially available on eMolecules.com"}, {"color": "#3ddbd9", "label": "Molecule commercially available from a database"}, {"color": "#ce4e04", "label": "Not able to find a synthetic path"}, {"color": "#f1c21b", "label": "Molecule from file"}], "wizardParameters": null, "siblings": [], "metaData": {"max_steps": 3, "steps": 0}, "isInteractive": false, "name": "test_0_20240316_12:40:26.466", "productMolecule": {"id": "5e93b8306051b700016a7b0d", "metadata": {}, "embed": {}, "computedFields": {}, "createdOn": 1586739248371, "createdBy": "system", "modifiedOn": 1586739248371, "modifiedBy": "system", "smiles": "CCN(CC)C(=O)c1cccc(C)c1", "reactionId": null, "projectId": "5e7322caa351d90001369032", "retrosynthesisId": "5e93b7fb6051b700016a7b0a", "type": "RETROSYNTHESIS", "moleculeImage": "<?xml version='1.0' encoding='UTF-8'?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<svg version='1.2' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='32.2mm' height='17.48mm' viewBox='0 0 32.2 17.48'>\n  <desc>Generated by the Chemistry Development Kit (http://github.com/cdk)</desc>\n  <g stroke-linecap='round' stroke-linejoin='round' stroke='#000000' stroke-width='.21' fill='#FF0D0D'>\n    <rect x='.0' y='.0' width='33.0' height='18.0' fill='#FFFFFF' stroke='none'/>\n    <g id='mol1' class='mol'>\n      <line id='mol1bnd1' class='bond' x1='.7' y1='9.16' x2='5.1' y2='6.61'/>\n      <line id='mol1bnd2' class='bond' x1='5.1' y1='6.61' x2='8.44' y2='8.53'/>\n      <line id='mol1bnd3' class='bond' x1='9.5' y1='10.49' x2='9.51' y2='14.23'/>\n      <line id='mol1bnd4' class='bond' x1='9.51' y1='14.23' x2='5.12' y2='16.77'/>\n      <line id='mol1bnd5' class='bond' x1='10.56' y1='8.53' x2='13.9' y2='6.6'/>\n      <g id='mol1bnd6' class='bond'>\n        <line x1='13.49' y1='6.83' x2='13.48' y2='2.9'/>\n        <line x1='14.3' y1='6.83' x2='14.3' y2='2.89'/>\n      </g>\n      <line id='mol1bnd7' class='bond' x1='13.9' y1='6.6' x2='18.3' y2='9.13'/>\n      <g id='mol1bnd8' class='bond'>\n        <line x1='18.3' y1='9.13' x2='18.32' y2='14.18'/>\n        <line x1='19.12' y1='9.6' x2='19.13' y2='13.71'/>\n      </g>\n      <line id='mol1bnd9' class='bond' x1='18.32' y1='14.18' x2='22.72' y2='16.72'/>\n      <g id='mol1bnd10' class='bond'>\n        <line x1='22.72' y1='16.72' x2='27.1' y2='14.21'/>\n        <line x1='22.72' y1='15.79' x2='26.29' y2='13.74'/>\n      </g>\n      <line id='mol1bnd11' class='bond' x1='27.1' y1='14.21' x2='27.1' y2='9.13'/>\n      <line id='mol1bnd12' class='bond' x1='27.1' y1='9.13' x2='31.5' y2='6.59'/>\n      <g id='mol1bnd13' class='bond'>\n        <line x1='27.1' y1='9.13' x2='22.7' y2='6.59'/>\n        <line x1='26.29' y1='9.6' x2='22.7' y2='7.53'/>\n      </g>\n      <line id='mol1bnd14' class='bond' x1='18.3' y1='9.13' x2='22.7' y2='6.59'/>\n      <path id='mol1atm3' class='atom' d='M8.8 8.22h.33l.82 1.54v-1.54h.24v1.85h-.34l-.82 -1.54v1.54h-.24v-1.85z' stroke='none' fill='#3050F8'/>\n      <path id='mol1atm7' class='atom' d='M13.89 .76q-.27 .0 -.43 .2q-.16 .2 -.16 .55q.0 .35 .16 .55q.16 .2 .43 .2q.27 .0 .43 -.2q.16 -.2 .16 -.55q.0 -.35 -.16 -.55q-.16 -.2 -.43 -.2zM13.89 .56q.39 .0 .62 .26q.23 .26 .23 .7q.0 .44 -.23 .7q-.23 .26 -.62 .26q-.39 .0 -.62 -.26q-.23 -.26 -.23 -.7q.0 -.43 .23 -.7q.23 -.26 .62 -.26z' stroke='none'/>\n    </g>\n  </g>\n</svg>\n", "moleculeUpdated": true, "moleculeName": "DETA"}, "predictionStats": null, "aiModel": "", "uploadedFile": null, "isFromFile": false, "isRenameable": true, "isFavorite": false, "isDeletable": true, "isAiModelDeleted": false, "isCustom": false}, "metadata": {"uiMessages": {"errors": [], "infos": [], "warnings": []}, "extendedPagination": {}}}}
`

**Comment by summmerF** [comment]
Yes, here is the full response:
`{'prediction_id': '65f7a9e29d16ec001f1d5345', 'response': {'payload': {'id': '65f7a9e29d16ec001f1d5345', 'metadata': {}, 'embed': {}, 'computedFields': {}, 'createdOn': 1710729698106, 'createdBy': 'f4448e77-fcf6-4f49-b3b4-4fa250772dd4', 'modifiedOn': 1710729698216, 'modifiedBy': 'f4448e77-fcf6-4f49-b3b4-4fa250772dd4', 'projectId': '6597fcf90fb57c001f9699bb', 'project': {'createdOn': 1704459513073, 'createdBy': 'f4448e77-fcf6-4f49-b3b4-4fa250772dd4', 'modifiedOn': 1704459513073, 'modifiedBy': 'f4448e77-fcf6-4f49-b3b4-4fa250772dd4', 'name': 'test_0', 'description': None, 'visibility': None, 'collectionDB': '', 'id': '6597fcf90fb57c001f9699bb'}, 'status': 'NEW', 'errorMessage': None, 'task': {'finished_time': 0.0, 'metaData': {}, 'queued_time': None, 'started_time': 0.0, 'status': 'WAITING', 'expected_start': 0.0, 'queue_position': 0, 'task_id': '3b49ac17-1b5d-45d3-9980-ee500dba0c23', 'retrieval_time': 0.0, 'retry': 0, 'counters': {'backward_prediction': 0, 'forward_prediction': 0}}, 'molecules': [], 'sequences': [], 'sequencesIds': None, 'legend': [{'color': '#002d9c', 'label': 'Common molecule available by default'}, {'color': '#0f62fe', 'label': 'Molecule available using a model-specific database'}, {'color': '#28a30d', 'label': 'Molecule commercially available on eMolecules.com'}, {'color': '#3ddbd9', 'label': 'Molecule commercially available from a database'}, {'color': '#ce4e04', 'label': 'Not able to find a synthetic path'}, {'color': '#f1c21b', 'label': 'Molecule from file'}], 'wizardParameters': None, 'siblings': [], 'metaData': {'max_steps': 3, 'steps': 0}, 'isInteractive': False, 'name': 'test_0_20240318_02:41:38.106', 'productMolecule': {'id': '5e93b8306051b700016a7b0d', 'metadata': {}, 'embed': {}, 'computedFields': {}, 'createdOn': 1586739248371, 'createdBy': 'system', 'modifiedOn': 1586739248371, 'modifiedBy': 'system', 'smiles': 'CCN(CC)C(=O)c1cccc(C)c1', 'reactionId': None, 'projectId': '5e7322caa351d90001369032', 'retrosynthesisId': '5e93b7fb6051b700016a7b0a', 'type': 'RETROSYNTHESIS', 'moleculeImage': '<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n<svg version=\'1.2\' xmlns=\'http://www.w3.org/2000/svg\' xmlns:xlink=\'http://www.w3.org/1999/xlink\' width=\'32.2mm\' height=\'17.48mm\' viewBox=\'0 0 32.2 17.48\'>\n  <desc>Generated by the Chemistry Development Kit (http://github.com/cdk)</desc>\n  <g stroke-linecap=\'round\' stroke-linejoin=\'round\' stroke=\'#000000\' stroke-width=\'.21\' fill=\'#FF0D0D\'>\n    <rect x=\'.0\' y=\'.0\' width=\'33.0\' height=\'18.0\' fill=\'#FFFFFF\' stroke=\'none\'/>\n    <g id=\'mol1\' class=\'mol\'>\n      <line id=\'mol1bnd1\' class=\'bond\' x1=\'.7\' y1=\'9.16\' x2=\'5.1\' y2=\'6.61\'/>\n      <line id=\'mol1bnd2\' class=\'bond\' x1=\'5.1\' y1=\'6.61\' x2=\'8.44\' y2=\'8.53\'/>\n      <line id=\'mol1bnd3\' class=\'bond\' x1=\'9.5\' y1=\'10.49\' x2=\'9.51\' y2=\'14.23\'/>\n      <line id=\'mol1bnd4\' class=\'bond\' x1=\'9.51\' y1=\'14.23\' x2=\'5.12\' y2=\'16.77\'/>\n      <line id=\'mol1bnd5\' class=\'bond\' x1=\'10.56\' y1=\'8.53\' x2=\'13.9\' y2=\'6.6\'/>\n      <g id=\'mol1bnd6\' class=\'bond\'>\n        <line x1=\'13.49\' y1=\'6.83\' x2=\'13.48\' y2=\'2.9\'/>\n        <line x1=\'14.3\' y1=\'6.83\' x2=\'14.3\' y2=\'2.89\'/>\n      </g>\n      <line id=\'mol1bnd7\' class=\'bond\' x1=\'13.9\' y1=\'6.6\' x2=\'18.3\' y2=\'9.13\'/>\n      <g id=\'mol1bnd8\' class=\'bond\'>\n        <line x1=\'18.3\' y1=\'9.13\' x2=\'18.32\' y2=\'14.18\'/>\n        <line x1=\'19.12\' y1=\'9.6\' x2=\'19.13\' y2=\'13.71\'/>\n      </g>\n      <line id=\'mol1bnd9\' class=\'bond\' x1=\'18.32\' y1=\'14.18\' x2=\'22.72\' y2=\'16.72\'/>\n      <g id=\'mol1bnd10\' class=\'bond\'>\n        <line x1=\'22.72\' y1=\'16.72\' x2=\'27.1\' y2=\'14.21\'/>\n        <line x1=\'22.72\' y1=\'15.79\' x2=\'26.29\' y2=\'13.74\'/>\n      </g>\n      <line id=\'mol1bnd11\' class=\'bond\' x1=\'27.1\' y1=\'14.21\' x2=\'27.1\' y2=\'9.13\'/>\n      <line id=\'mol1bnd12\' class=\'bond\' x1=\'27.1\' y1=\'9.13\' x2=\'31.5\' y2=\'6.59\'/>\n      <g id=\'mol1bnd13\' class=\'bond\'>\n        <line x1=\'27.1\' y1=\'9.13\' x2=\'22.7\' y2=\'6.59\'/>\n        <line x1=\'26.29\' y1=\'9.6\' x2=\'22.7\' y2=\'7.53\'/>\n      </g>\n      <line id=\'mol1bnd14\' class=\'bond\' x1=\'18.3\' y1=\'9.13\' x2=\'22.7\' y2=\'6.59\'/>\n      <path id=\'mol1atm3\' class=\'atom\' d=\'M8.8 8.22h.33l.82 1.54v-1.54h.24v1.85h-.34l-.82 -1.54v1.54h-.24v-1.85z\' stroke=\'none\' fill=\'#3050F8\'/>\n      <path id=\'mol1atm7\' class=\'atom\' d=\'M13.89 .76q-.27 .0 -.43 .2q-.16 .2 -.16 .55q.0 .35 .16 .55q.16 .2 .43 .2q.27 .0 .43 -.2q.16 -.2 .16 -.55q.0 -.35 -.16 -.55q-.16 -.2 -.43 -.2zM13.89 .56q.39 .0 .62 .26q.23 .26 .23 .7q.0 .44 -.23 .7q-.23 .26 -.62 .26q-.39 .0 -.62 -.26q-.23 -.26 -.23 -.7q.0 -.43 .23 -.7q.23 -.26 .62 -.26z\' stroke=\'none\'/>\n    </g>\n  </g>\n</svg>\n', 'moleculeUpdated': True, 'moleculeName': 'DETA'}, 'predictionStats': None, 'aiModel': '', 'uploadedFile': None, 'isFromFile': False, 'isRenameable': True, 'isFavorite': False, 'isDeletable': True, 'isAiModelDeleted': False, 'isCustom': False}, 'metadata': {'uiMessages': {'errors': [], 'infos': [], 'warnings': []}, 'extendedPagination': {}}}}
`

Although the response['status'] is NEW, it seems to get ‘results’ from it after a while. 

Get 4 nodeids, and the last one is successful to 'get_reaction_settings':
![image](https://github.com/rxn4chemistry/rxn4chemistry/assets/94446867/c50629a7-9f1b-4a48-a76a-e0836867b93e)

**Comment by drugilsberg** [comment]
Apologies for the delay in the reply, looking at the response, this behaviour is expected. You have to fully validate and fix quantities/actions in children nodes before getting a successful validation in the parent nodes. What you see here is basically this behaviour. The synthesis manipulation is something that is better done via the UI and the API interface can be a bit cryptic and tricky to use for such use cases.
